parameters:
#    cacic_common.example.class: Cacic\CommonBundle\Example
    cacic_senha_algorithm: sha1

services:
    cacic.twig.siglas_extension:
        class: Cacic\CommonBundle\Twig\SiglasExtension
        tags:
            - { name: twig.extension }
    cacic.twig.bundles_extension:
        class: Cacic\CommonBundle\Twig\BundlesExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }

    login_listener:
        class: 'Cacic\CommonBundle\Listener\LoginListener'
        arguments: ['@security.context', '@doctrine']
        tags:
        - { name: 'kernel.event_listener', event: 'security.interactive_login' }
