cacic_relatorio_autorizacoes:
    pattern: /autorizacoes
    defaults: { _controller: CacicRelatorioBundle:Default:autorizacoes }

cacic_relatorio_faturamento:
    pattern: /faturamento
    defaults: { _controller: CacicRelatorioBundle:Faturamento:index }
    requirements:
        _method: GET

cacic_relatorio_resultado:
     pattern: /faturamento
     defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoRelatorio }
     requirements:
         _method: POST

cacic_relatorio_faturamento_listar:
    pattern: /software/faturamento/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listar, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_patrimonio:
    pattern: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonio }
    requirements:
        _method: GET

cacic_relatorio_patrimonio_relatorios:
    pattern: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonioRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_inventariados:
    pattern: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariados }
    requirements:
        _method: GET

cacic_relatorio_software_inventariados_rel:
    pattern: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariadosRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_listar:
    pattern: /software/listar/{idSoftware}
    defaults: { _controller: CacicRelatorioBundle:Software:listar, idSoftware: null }
    requirements:
        idSoftware: \d+

cacic_relatorio_software_licenciados:
    pattern: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciados }
    requirements:
        _method: GET

cacic_relatorio_software_licenciados_rel:
    pattern: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciadosRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_orgao:
    pattern: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgao }
    requirements:
        _method: GET

cacic_relatorio_software_orgao_rel:
    pattern: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgaoRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_aquisicoes:
    pattern: /software/aquisicoes
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesRelatorio }

cacic_relatorio_software_tipo:
    pattern: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipo }
    requirements:
        _method: GET

cacic_relatorio_software_tipo_rel:
    pattern: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipoRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_naoVinculados:
    pattern: /software/naovinculados
    defaults: { _controller: CacicRelatorioBundle:Software:naoVinculadosRelatorio }

cacic_relatorio_hardware_configuracoes:
    pattern: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoes }
    requirements:
        _method: GET

cacic_relatorio_hardware_configuracoes_rel:
    pattern: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoesRelatorio }
    requirements:
        _method: POST

cacic_relatorio_hardware_wmi:
    pattern: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmi }
    requirements:
            _method: GET

cacic_relatorio_hardware_wmi_rel:
    pattern: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorio }
    requirements:
            _method: POST

cacic_relatorio_software_lista:
    pattern: /software/inventariados/{nmSoftware}/{nmLocal}
    defaults: { _controller: CacicRelatorioBundle:Software:lista, nmSoftware:null, nmLocal:null }

cacic_relatorio_hardware_wmi_detalhe:
    pattern: /hardware/{classe}/{propriedade}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorioDetalhe }

cacic_relatorio_inativos:
    pattern: /inativos
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativos }
    requirements:
        _method: GET

cacic_relatorio_inativos_rel:
     pattern: /inativos
     defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosRelatorio }
     requirements:
         _method: POST

cacic_relatorio_inativos_listar:
    pattern: /inativos/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarInativos, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

