cacic_relatorio_autorizacoes:
    pattern: /autorizacoes
    defaults: { _controller: CacicRelatorioBundle:Default:autorizacoes }

cacic_relatorio_faturamento:
    pattern: /faturamento
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamento }
    requirements:
        _method: GET

cacic_relatorio_resultado:
     pattern: /faturamento
     defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoRelatorio }
     requirements:
         _method: POST

cacic_relatorio_faturamento_listar:
    pattern: /software/faturamento/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listar, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_patrimonio:
    pattern: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonio }
    requirements:
        _method: GET

cacic_relatorio_patrimonio_relatorios:
    pattern: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonioRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_inventariados:
    pattern: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariados }
    requirements:
        _method: GET

cacic_relatorio_software_inventariados_csv:
    pattern: /software/inventariados/csv
    defaults: { _controller: CacicRelatorioBundle:Software:inventariadosRelatorioCsv }
    requirements:
        _method: POST

cacic_relatorio_software_inventariados_rel:
    pattern: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariadosRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_listar:
    pattern: /software/listar/{idSoftware}
    defaults: { _controller: CacicRelatorioBundle:Software:listar, idSoftware: null }
    requirements:
        idSoftware: \d+

cacic_relatorio_software_licenciados:
    pattern: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciados }
    requirements:
        _method: GET

cacic_relatorio_software_licenciados_rel:
    pattern: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciadosRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_orgao:
    pattern: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgao }
    requirements:
        _method: GET

cacic_relatorio_software_orgao_rel:
    pattern: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgaoRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_aquisicoes:
    pattern: /software/aquisicoes
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesRelatorio }

cacic_relatorio_software_aquisicoes_det:
    pattern: /software/aquisicoes/{idAquisicao}/{idTipoLicenca}
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesDetalhado }

cacic_relatorio_software_tipo:
    pattern: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipo }
    requirements:
        _method: GET

cacic_relatorio_software_tipo_rel:
    pattern: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipoRelatorio }
    requirements:
        _method: POST

cacic_relatorio_software_naoVinculados:
    pattern: /software/naovinculados
    defaults: { _controller: CacicRelatorioBundle:Software:naoVinculadosRelatorio }

cacic_relatorio_hardware_configuracoes:
    pattern: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoes }
    requirements:
        _method: GET

cacic_relatorio_hardware_configuracoes_rel:
    pattern: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoesRelatorio }
    requirements:
        _method: POST

cacic_relatorio_hardware_wmi:
    pattern: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmi }
    requirements:
            _method: GET

cacic_relatorio_hardware_wmi_rel:
    pattern: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorio }
    requirements:
            _method: POST

cacic_relatorio_wmi_sem_coleta:
    pattern: /wmi/semcoleta
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColeta }

cacic_relatorio_wmi_sem_coleta_listar:
    pattern: /wmi/semcoletalistar
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaListar }

cacic_relatorio_wmi_sem_coleta_listar_csv:
    pattern: /wmi/semcoletalistar/csv
    defaults: { _controller: CacicRelatorioBundle:Hardware:listarWmiSemColetaCsv}

cacic_relatorio_wmi_sem_coleta_detalhar:
    pattern: /wmi/semcoletadetalhar
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaDetalhar }

cacic_relatorio_wmi_sem_coleta_detalhar_csv:
    pattern: /wmi/semcoletadetalhar/csv
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaDetalharCsv }

cacic_relatorio_hardware_wmi_dinamico:
    pattern: /relWmiDinamico
    defaults: { _controller: CacicRelatorioBundle:Hardware:relWmiDinamico }

cacic_relatorio_dinamico_detalhar:
    pattern: /relWmiDinamico/detalhar
    defaults: { _controller: CacicRelatorioBundle:Hardware:relWmiDinamicoDetalhar }

cacic_relatorio_software_lista:
    pattern: /software/inventariados/{nmSoftware}/{nmLocal}/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Software:lista, nmSoftware:null, nmLocal:null, idRede:null }

cacic_relatorio_hardware_wmi_detalhe:
    pattern: /hardware/{classe}/{propriedade}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorioDetalhe }

cacic_relatorio_inativos:
    pattern: /inativos
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativos }
    requirements:
        _method: GET

cacic_relatorio_inativos_rel:
     pattern: /inativos
     defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosRelatorio }
     requirements:
         _method: POST

cacic_relatorio_inativos_listar:
    pattern: software/inativos/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarInativos, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_faturamento_csv:
    pattern: /faturamento/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoCsv }
    requirements:
        _method: POST

cacic_faturamento_csv_interno:
    pattern: /faturamento/csv/interno
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoCsvInterno }
    requirements:
        _method: POST

cacic_inativos_csv:
    pattern: /inativos/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosCsv }
    requirements:
        _method: GET

cacic_inativos_csv_inicial:
    pattern: /inativos/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosCsv }
    requirements:
     _method: POST

cacic_faturamento_listar_csv:
    pattern: /faturamento/listar/csv/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_inativos_listar_csv:
    pattern: /inativos/listar/csv/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarInativosCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_csv_hardware_wmi:
    pattern: /csv/hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:csvWMIRelatorio }

cacic_relatorio_csv_hardware_wmi_detalhe:
    pattern: /csv/hardware/{classe}/{propriedade}
    defaults: { _controller: CacicRelatorioBundle:Hardware:csvWMIRelatorioDetalhe }

    defaults: { _controller: CacicRelatorioBundle:Hardware:csvWMIRelatorioDetalhe }

cacic_faturamento_computador:
    pattern: /faturamento/computador
    defaults: { _controller: CacicRelatorioBundle:Faturamento:computador }

cacic_relatorio_usuario:
    pattern: /usuario
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuario }

cacic_relatorio_usuario_detalhar:
    pattern: /usuario/detalhar
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioDetalhar }

cacic_relatorio_usuario_csv:
    pattern: /usuario/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioCsv }

cacic_relatorio_usuario_csv_dinamico:
    pattern: /usuario/csvDinamico
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioCsvDinamico }

cacic_relatorio_usuario_historico:
    pattern: /usuario/historico/{te_ultimo_login}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioHistorico, te_ultimo_login: null}

cacic_computador_historico:
  pattern: /computador/historico/{idComputador}/{classe}
  defaults: { _controller: CacicRelatorioBundle:Computador:historico, idComputador: null, classe: null}
  requirements:
    idComputador: \d+

cacic_software_search:
  pattern: /search/software/{name}
  defaults: { _controller:CacicRelatorioBundle:Software:search, name:null }
  requirements:
    _method: GET

cacic_relatorio_software_aquisicoes_det_csv:
    pattern: /software/aquisicoes/{idAquisicao}/{idTipoLicenca}/csv
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesDetalhadoCsv }

cacic_relatorio_computador:
    pattern: /computador
    defaults: { _controller: CacicRelatorioBundle:Computador:listar }
    requirements:
        _method: GET

cacic_relatorio_computador_resultado:
     pattern: /computador/subredes
     defaults: { _controller: CacicRelatorioBundle:Computador:listarResultado }

cacic_relatorio_computador_resultado_csv:
     pattern: /computador/subredes/csv
     defaults: { _controller: CacicRelatorioBundle:Computador:listarResultadoCsv }

cacic_relatorio_computador_listar:
    pattern: /computador/listar/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Computador:listarDetalhado, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_computador_listar_csv:
    pattern: /computador/listar/csv/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Computador:listarDetalhadoCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_so:
    pattern: /so
    defaults: { _controller: CacicRelatorioBundle:So:index }

cacic_relatorio_so_listar:
    pattern: /so/listar
    defaults: { _controller: CacicRelatorioBundle:So:listar, idSo: null }

cacic_relatorio_so_listar_csv:
    pattern: /so/listar/csv
    defaults: { _controller: CacicRelatorioBundle:So:listarCsv, idSo: null }

cacic_relatorio_so_detalhar:
    pattern: /so/detalhar/{idSo}
    defaults: { _controller: CacicRelatorioBundle:So:detalhar }

cacic_relatorio_so_detalhar_csv:
    pattern: /so/detalhar/csv/{idSo}
    defaults: { _controller: CacicRelatorioBundle:So:detalharCsv }

cacic_relatorio_so_consolidado:
    pattern: /so/consolidado
    defaults: { _controller: CacicRelatorioBundle:So:consolidado }

cacic_relatorio_so_consolidado_csv:
    pattern: /so/consolidado/csv
    defaults: { _controller: CacicRelatorioBundle:So:consolidadoCsv }