cacic_relatorio_autorizacoes:
    path: /autorizacoes
    defaults: { _controller: CacicRelatorioBundle:Default:autorizacoes }

cacic_relatorio_faturamento:
    path: /faturamento
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamento }
    methods: ['GET']

cacic_relatorio_resultado:
     path: /faturamento
     defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoRelatorio }
     methods: ['POST']

cacic_relatorio_faturamento_listar:
    path: /hardware/faturamento/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listar, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_patrimonio:
    path: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonio }
    methods: ['GET']

cacic_relatorio_patrimonio_relatorios:
    path: /patrimonio
    defaults: { _controller: CacicRelatorioBundle:Default:patrimonioRelatorio }
    methods: ['POST']

cacic_relatorio_software_inventariados:
    path: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariados }
    methods: ['GET']

cacic_relatorio_software_inventariados_csv:
    path: /software/inventariados/csv
    defaults: { _controller: CacicRelatorioBundle:Software:inventariadosRelatorioCsv }
    methods: ['POST']

cacic_relatorio_software_inventariados_rel:
    path: /software/inventariados
    defaults: { _controller: CacicRelatorioBundle:Software:inventariadosRelatorio }
    methods: ['POST']

cacic_relatorio_software_listar:
    path: /software/listar/{idSoftware}
    defaults: { _controller: CacicRelatorioBundle:Software:listar, idSoftware: null }
    requirements:
        idSoftware: \d+

cacic_relatorio_software_licenciados:
    path: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciados }
    methods: ['GET']

cacic_relatorio_software_licenciados_rel:
    path: /software/licenciados
    defaults: { _controller: CacicRelatorioBundle:Software:licenciadosRelatorio }
    methods: ['POST']

cacic_relatorio_software_orgao:
    path: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgao }
    methods: ['GET']

cacic_relatorio_software_orgao_rel:
    path: /software/orgao
    defaults: { _controller: CacicRelatorioBundle:Software:orgaoRelatorio }
    methods: ['POST']

cacic_relatorio_software_aquisicoes:
    path: /software/aquisicoes
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesRelatorio }

cacic_relatorio_software_aquisicoes_det:
    path: /software/aquisicoes/{idAquisicao}/{idTipoLicenca}
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesDetalhado }

cacic_relatorio_software_tipo:
    path: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipo }
    methods: ['GET']

cacic_relatorio_software_tipo_rel:
    path: /software/tipo
    defaults: { _controller: CacicRelatorioBundle:Software:tipoRelatorio }
    methods: ['POST']

cacic_relatorio_software_naoVinculados:
    path: /software/naovinculados
    defaults: { _controller: CacicRelatorioBundle:Software:naoVinculadosRelatorio }

cacic_relatorio_hardware_configuracoes:
    path: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoes }
    methods: ['GET']

cacic_relatorio_hardware_configuracoes_rel:
    path: /hardware/configuracoes
    defaults: { _controller: CacicRelatorioBundle:Hardware:configuracoesRelatorio }
    methods: ['POST']

cacic_relatorio_hardware_wmi:
    path: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmi }
    methods: ['GET']

cacic_relatorio_hardware_wmi_rel:
    path: /hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorio }
    methods: ['POST']

cacic_relatorio_wmi_sem_coleta:
    path: /wmi/semcoleta
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColeta }

cacic_relatorio_wmi_sem_coleta_listar:
    path: /wmi/semcoletalistar
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaListar }

cacic_relatorio_wmi_sem_coleta_listar_csv:
    path: /wmi/semcoletalistar/csv
    defaults: { _controller: CacicRelatorioBundle:Hardware:listarWmiSemColetaCsv}

cacic_relatorio_wmi_sem_coleta_detalhar:
    path: /wmi/semcoletadetalhar
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaDetalhar }

cacic_relatorio_wmi_sem_coleta_detalhar_csv:
    path: /wmi/semcoletadetalhar/csv
    defaults: { _controller: CacicRelatorioBundle:Hardware:semColetaDetalharCsv }

cacic_relatorio_hardware_wmi_dinamico:
    path: /relWmiDinamico
    defaults: { _controller: CacicRelatorioBundle:Hardware:relWmiDinamico }

cacic_relatorio_dinamico_detalhar:
    path: /relWmiDinamico/detalhar
    defaults: { _controller: CacicRelatorioBundle:Hardware:relWmiDinamicoDetalhar }

cacic_relatorio_csv_wmi_dinamico:
    path: /relWmiDinamico/csvRelWmiDinamico
    defaults: { _controller: CacicRelatorioBundle:Hardware:csvRelWmiDinamico }

cacic_relatorio_software_lista:
    path: /software/inventariados/{nmSoftware}/{nmLocal}/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Software:lista, nmSoftware:null, nmLocal:null, idRede:null }

cacic_relatorio_hardware_wmi_detalhe:
    path: /hardware/{classe}/{propriedade}
    defaults: { _controller: CacicRelatorioBundle:Hardware:wmiRelatorioDetalhe }

cacic_relatorio_inativos:
    path: /inativos
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativos }
    methods: ['GET']

cacic_relatorio_inativos_rel:
     path: /inativos
     defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosRelatorio }
     methods: ['POST']

cacic_relatorio_inativos_listar:
    path: software/inativos/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarInativos, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_faturamento_csv:
    path: /faturamento/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoCsv }
    methods: ['POST']

cacic_faturamento_csv_interno:
    path: /faturamento/csv/interno
    defaults: { _controller: CacicRelatorioBundle:Faturamento:faturamentoCsvInterno }
    methods: ['POST']

cacic_inativos_csv:
    path: /inativos/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosCsv }
    methods: ['GET']

cacic_inativos_csv_inicial:
    path: /inativos/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:inativosCsv }
    methods: ['POST']

cacic_faturamento_listar_csv:
    path: /faturamento/listar/csv/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_inativos_listar_csv:
    path: /inativos/listar/csv/{idRede}/{dtAcaoInicio}/{dtAcaoFim}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:listarInativosCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_csv_hardware_wmi:
    path: /csv/hardware/{classe}
    defaults: { _controller: CacicRelatorioBundle:Hardware:csvWMIRelatorio }

cacic_relatorio_csv_hardware_wmi_detalhe:
    path: /csv/hardware/{classe}/{propriedade}
    defaults: { _controller: CacicRelatorioBundle:Hardware:csvWMIRelatorioDetalhe }

cacic_faturamento_computador:
    path: /faturamento/computador
    defaults: { _controller: CacicRelatorioBundle:Faturamento:computador }

cacic_relatorio_usuario:
    path: /usuario
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuario }

cacic_relatorio_usuario_detalhar:
    path: /usuario/detalhar
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioDetalhar }

cacic_relatorio_usuario_csv:
    path: /usuario/csv
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioCsv }

cacic_relatorio_usuario_csv_dinamico:
    path: /usuario/csvDinamico
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioCsvDinamico }

cacic_relatorio_usuario_historico:
    path: /usuario/historico/{te_ultimo_login}
    defaults: { _controller: CacicRelatorioBundle:Faturamento:usuarioHistorico, te_ultimo_login: null}

cacic_computador_historico:
  path: /computador/historico/{idComputador}/{classe}
  defaults: { _controller: CacicRelatorioBundle:Computador:historico, idComputador: null, classe: null}
  requirements:
    idComputador: \d+

cacic_software_search:
  path: /search/software/{name}
  defaults: { _controller:CacicRelatorioBundle:Software:search, name:null }
  methods: ['GET']

cacic_relatorio_software_aquisicoes_det_csv:
    path: /software/aquisicoes/{idAquisicao}/{idTipoLicenca}/csv
    defaults: { _controller: CacicRelatorioBundle:Software:aquisicoesDetalhadoCsv }

cacic_relatorio_computador:
    path: /computador
    defaults: { _controller: CacicRelatorioBundle:Computador:listar }
    methods: ['GET']

cacic_relatorio_computador_resultado:
     path: /computador/subredes
     defaults: { _controller: CacicRelatorioBundle:Computador:listarResultado }

cacic_relatorio_computador_resultado_csv:
     path: /computador/subredes/csv
     defaults: { _controller: CacicRelatorioBundle:Computador:listarResultadoCsv }

cacic_relatorio_computador_listar:
    path: /computador/listar/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Computador:listarDetalhado, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_computador_listar_csv:
    path: /computador/listar/csv/{idRede}
    defaults: { _controller: CacicRelatorioBundle:Computador:listarDetalhadoCsv, idRede: null, dtAcaoInicio: null, dtAcaoFim: null }
    requirements:
        idRede: \d+

cacic_relatorio_computador_log_acesso:
    path:  /computador/log/acesso/{idComputador}
    defaults: { _controller: CacicRelatorioBundle:Computador:logAcesso, idComputador: null }
    requirements:
        idComputador: \d+

cacic_relatorio_computador_log_acesso_csv:
    path:  /computador/log/acesso/{idComputador}/csv
    defaults: { _controller: CacicRelatorioBundle:Computador:logAcessoCsv, idComputador: null }
    requirements:
        idComputador: \d+

cacic_relatorio_computador_log_usuario:
    path:  /computador/log/usuario/{idComputador}
    defaults: { _controller: CacicRelatorioBundle:Computador:logUsuario, idComputador: null }
    requirements:
        idComputador: \d+

cacic_relatorio_computador_log_usuario_csv:
    path:  /computador/log/usuario/{idComputador}/csv
    defaults: { _controller: CacicRelatorioBundle:Computador:logUsuarioCsv, idComputador: null }
    requirements:
        idComputador: \d+

cacic_relatorio_so:
    path: /so
    defaults: { _controller: CacicRelatorioBundle:So:index }

cacic_relatorio_so_listar:
    path: /so/listar
    defaults: { _controller: CacicRelatorioBundle:So:listar, idSo: null }

cacic_relatorio_so_listar_csv:
    path: /so/listar/csv
    defaults: { _controller: CacicRelatorioBundle:So:listarCsv, idSo: null }

cacic_relatorio_so_detalhar:
    path: /so/detalhar/{idSo}
    defaults: { _controller: CacicRelatorioBundle:So:detalhar }

cacic_relatorio_so_detalhar_csv:
    path: /so/detalhar/csv/{idSo}
    defaults: { _controller: CacicRelatorioBundle:So:detalharCsv }

cacic_relatorio_so_consolidado:
    path: /so/consolidado
    defaults: { _controller: CacicRelatorioBundle:So:consolidado }

cacic_relatorio_so_consolidado_csv:
    path: /so/consolidado/csv
    defaults: { _controller: CacicRelatorioBundle:So:consolidadoCsv }

cacic_relatorio_software_cadastrar:
    path: /software/cadastrar/{idRelatorio}
    defaults: { _controller: CacicRelatorioBundle:Software:cadastrar, idRelatorio: null }

cacic_relatorio_software_relatorio:
    path: /software
    defaults: { _controller: CacicRelatorioBundle:Software:softwares }

cacic_relatorio_software_nome:
    path: /software/nome
    defaults: { _controller: CacicRelatorioBundle:Software:nome }