services:
    form.type.software_relatorio:
        class: Cacic\RelatorioBundle\Form\Type\SoftwareRelatorioType
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: form.type, alias: relatorio_software }