parameters:
    webservice_user_provider.class: Cacic\WSBundle\Security\User\WebserviceUserProvider

services:
    cacic.twig.old_cacic_extension:
        class: Cacic\WSBundle\Twig\OldCacicExtension
        tags:
            - { name: twig.extension }

    cacic.commonbundle.helper.old_cacic_helper:
        class: Cacic\CommonBundle\Helper\OldCacicHelper
        arguments: [@kernel]

    webservice_user_provider:
        class: "%webservice_user_provider.class%"
        arguments: [@service_container]