imports:
    - { resource: config.yml }

framework:
    trusted_proxies: [10.0.0.0/8]
    profiler: { enabled: false }

doctrine:
    orm:
        auto_mapping: true
        metadata_cache_driver: apc
        result_cache_driver: apc
        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed # or buffer
            level:        error
            handler:      lexik_monolog_browser
        app:
            type:         buffer
            action_level: error
            channels:     app
            handler:      lexik_monolog_browser
        lexik_monolog_browser:
            type:         service
            id:           lexik_monolog_browser.handler.doctrine_dbal

swiftmailer:
    sender_address: www-data@localhost
