imports:
    - { resource: config_prod.yml }
    - { resource: "@CacicMultiBundle/Resources/config/services.yml" }

framework:
    router: { resource: "%kernel.root_dir%/config/routing_multi.yml" }

doctrine:
    dbal:
      default_connection: dynamic
      connections:
        dynamic:
          driver:   %database_driver%
          host:     %database_host%
          port:     %database_port%
          dbname:   'empty_database'
          charset:  UTF8
          wrapper_class: 'Cacic\MultiBundle\Connection\ConnectionWrapper'