cacic_multi_command_fixtures:
  path: /command/fixtures
  defaults: { _controller: CacicMultiBundle:Command:fixturesLoad }

cacic_multi_command_site:
  path: /command/site
  defaults: { _controller: CacicMultiBundle:Command:createSite }

cacic_multi_command_schema:
  path: /command/schema
  defaults: { _controller: CacicMultiBundle:Command:schemaUpdate }