Cacic\CommonBundle\Entity\AquisicaoItem:
    type: entity
    table: aquisicao_item
    repositoryClass: Cacic\CommonBundle\Entity\AquisicaoItemRepository
    fields:
        idAquisicaoItem:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_aquisicao_item
            generator:
                strategy: IDENTITY
        qtLicenca:
            type: integer
            unsigned: false
            nullable: true
            column: qt_licenca
        dtVencimentoLicenca:
            type: date
            nullable: true
            column: dt_vencimento_licenca
        teObs:
            type: text
            fixed: false
            nullable: true
            column: te_obs
    manyToOne:
        idAquisicao:
            targetEntity: Aquisicao
            cascade: {  }
            mappedBy: null
            inversedBy: itens
            joinColumns:
                id_aquisicao:
                    referencedColumnName: id_aquisicao
            orphanRemoval: false
        idTipoLicenca:
            targetEntity: TipoLicenca
            joinColumns:
                id_tipo_licenca:
                    referencedColumnName: id_tipo_licenca
            orphanRemoval: false
        idSoftwareRelatorio:
            targetEntity: SoftwareRelatorio
            inversedBy: aquisicoes
            joinColumns:
                id_software_relatorio:
                    referencedColumnName: id_relatorio
    oneToMany:
        idSoftwareEstacao:
            targetEntity: SoftwareEstacao
            mappedBy: idAquisicaoItem
    lifecycleCallbacks: {  }
