Cacic\CommonBundle\Entity\Aquisicao:
    type: entity
    table: aquisicao
    repositoryClass: Cacic\CommonBundle\Entity\AquisicaoRepository
    fields:
        idAquisicao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_aquisicao
            generator:
                strategy: IDENTITY
        dtAquisicao:
            type: date
            nullable: true
            column: dt_aquisicao
        nrProcesso:
            type: text
            fixed: true
            nullable: true
            column: nr_processo
        nmEmpresa:
            type: text
            fixed: true
            nullable: true
            column: nm_empresa
        nmProprietario:
            type: text
            fixed: true
            nullable: true
            column: nm_proprietario
        nrNotafiscal:
            type: text
            fixed: true
            nullable: true
            column: nr_notafiscal
    oneToMany:
        itens:
            targetEntity: AquisicaoItem
            mappedBy: idAquisicao
    lifecycleCallbacks: {  }
