Cacic\CommonBundle\Entity\ClassProperty:
    type: entity
    table: class_property
    repositoryClass: Cacic\CommonBundle\Entity\ClassPropertyRepository
    fields:
        idClassProperty:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_class_property
            generator:
                strategy: IDENTITY
        nmPropertyName:
            type: text
            fixed: false
            nullable: false
            column: nm_property_name
        prettyName:
            type: text
            fixed: false
            nullable: true
            column: pretty_name
        tePropertyDescription:
            type: text
            fixed: false
            nullable: true
            column: te_property_description
        nmFunctionPreDb:
            type: text
            fixed: false
            nullable: true
            column: nm_function_pre_db
        nmFunctionPosDb:
            type: text
            fixed: false
            nullable: true
            column: nm_function_pos_db
    manyToOne:
        idClass:
            targetEntity: Classe
            cascade: []
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class:
                    referencedColumnName: id_class
                    nullable: false
            orphanRemoval: false
    uniqueConstraints:
        class_property_uq_idx:
            columns: [nm_property_name, id_class]
    lifecycleCallbacks: {  }
