Cacic\CommonBundle\Entity\Classe:
    type: entity
    table: classe
    repositoryClass: Cacic\CommonBundle\Entity\ClasseRepository
    fields:
        idClass:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_class
            generator:
                strategy: IDENTITY
        nmClassName:
            type: text
            fixed: false
            nullable: false
            column: nm_class_name
        teClassDescription:
            type: text
            fixed: false
            nullable: false
            column: te_class_description
    uniqueConstraints:
        nm_class_uq_idx:
            columns: [nm_class_name]
    lifecycleCallbacks: {  }
