Cacic\CommonBundle\Entity\Computador:
    type: entity
    table: computador
    repositoryClass: Cacic\CommonBundle\Entity\ComputadorRepository
    fields:
        idComputador:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_computador
            generator:
                strategy: IDENTITY
        nmComputador:
            type: text
            fixed: false
            nullable: true
            column: nm_computador
        teNodeAddress:
            type: text
            fixed: true
            nullable: false
            column: te_node_address
        teIpComputador:
            type: text
            fixed: true
            nullable: true
            column: te_ip_computador
        dtHrInclusao:
            type: datetime
            nullable: true
            column: dt_hr_inclusao
        dtHrExclusao:
            type: datetime
            nullable: true
            column: dt_hr_exclusao
        dtHrUltAcesso:
            type: datetime
            nullable: true
            column: dt_hr_ult_acesso
        teVersaoCacic:
            type: text
            fixed: true
            nullable: true
            column: te_versao_cacic
        teVersaoGercols:
            type: text
            fixed: true
            nullable: true
            column: te_versao_gercols
        tePalavraChave:
            type: text
            fixed: true
            nullable: true
            column: te_palavra_chave
        forcaColeta:
            type: text
            nullable: true
            column: forca_coleta
        dtHrColetaForcadaEstacao:
            type: datetime
            nullable: true
            column: dt_hr_coleta_forcada_estacao
        teNomesCurtosModulos:
            type: text
            fixed: false
            nullable: true
            column: te_nomes_curtos_modulos
        idConta:
            type: integer
            unsigned: false
            nullable: true
            column: id_conta
        teDebugging:
            type: text
            nullable: true
            column: te_debugging
        teUltimoLogin:
            type: text
            fixed: false
            nullable: true
            column: te_ultimo_login
        dtDebug:
            type: text
            fixed: true
            nullable: true
            column: dt_debug
        isNotebook:
            type: text
            length: 3
            nullable: true
            column: is_notebook
        forcaPatrimonio:
            type: text
            lenght: 1
            nullable: true
            column: forca_patrimonio
        ativo:
            type: boolean
            nullable: true
            column: ativo
    oneToMany:
        softwares:
            targetEntity: SoftwareEstacao
            mappedBy: idComputador
        hardwares:
            targetEntity: ComputadorColeta
            mappedBy: computador
            fetch: EXTRA_LAZY
        software_coletado:
            targetEntity: PropriedadeSoftware
            mappedBy: computador
            fetch: EXTRA_LAZY
        hardwares_historico:
            targetEntity: ComputadorColetaHistorico
            mappedBy: computador
            fetch: EXTRA_LAZY
        erros_agente:
            targetEntity: ErrosAgente
            mappedBy: computador
        notifications:
            targetEntity: Notifications
            mappedBy: idComputador
    manyToOne:
        idUsuarioExclusao:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario_exclusao:
                    referencedColumnName: id_usuario
            orphanRemoval: false
        idSo:
            targetEntity: So
            cascade: []
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_so:
                    referencedColumnName: id_so
            orphanRemoval: false
        idRede:
            targetEntity: Rede
            cascade: []
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rede:
                    referencedColumnName: id_rede
            orphanRemoval: false
    uniqueConstraints:
        mac_os_unique_idx:
            columns: [ te_node_address, id_so ]
    lifecycleCallbacks: {  }
