Cacic\CommonBundle\Entity\ComputadorColeta:
    type: entity
    table: computador_coleta
    repositoryClass: Cacic\CommonBundle\Entity\ComputadorColetaRepository
    fields:
        idComputadorColeta:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_computador_coleta
            generator:
                strategy: IDENTITY
        teClassPropertyValue:
            type: text
            nullable: false
            column: te_class_property_value
        dtHrInclusao:
            type: datetime
            nullable: false
            column: dt_hr_inclusao
        ativo:
            type: boolean
            nullable: true
            column: ativo
        dtHrExclusao:
            type: datetime
            nullable: true
            column: dt_hr_exclusao
    manyToOne:
        idClasseColetaPropriedade:
            targetEntity: ClasseColetaPropriedades
            cascade: ["merge"]
            mappedBy: null
            inversedBy: coletas
            joinColumns:
                id_classe_coleta_propriedades:
                    referencedColumnName: id_classe_coleta_propriedades
                    nullable: false
            orphanRemoval: false
        classProperty:
            targetEntity: ClassProperty
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class_property:
                    referencedColumnName: id_class_property
                    nullable: false
            orphanRemoval: false
        idClass:
            targetEntity: Classe
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_class:
                    referencedColumnName: id_class
            orphanRemoval: false
    oneToMany:
        historico:
            targetEntity: ComputadorColetaHistorico
            mappedBy: computadorColeta
            fetch: EXTRA_LAZY
    uniqueConstraints:
        computador_coleta_index_idx:
            columns: [ id_classe_coleta_propriedades, id_class_property ]
    lifecycleCallbacks: {  }
