Cacic\CommonBundle\Entity\ErrosAgente:
    type: entity
    table: erros_agente
    repositoryClass: Cacic\CommonBundle\Entity\ErrosAgenteRepository
    fields:
        idErrosAgente:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_erros_agente
            generator:
                strategy: IDENTITY
        timestampErro:
            type: datetime
            nullable: false
            column: timestamp_erro
        nivelErro:
            type: text
            nullable: false
            column: nivel_erro
        mensagem:
            type: text
            nullable: false
            column: mensagem
    manyToOne:
            computador:
                targetEntity: Computador
                cascade: {  }
                mappedBy: null
                inversedBy: erros_agente
                joinColumns:
                    id_computador:
                        referencedColumnName: id_computador
                        nullable: false
                orphanRemoval: false
    lifecycleCallbacks: {  }