Cacic\CommonBundle\Entity\InsucessoInstalacao:
    type: entity
    table: insucesso_instalacao
    repositoryClass: Cacic\CommonBundle\Entity\InsucessoInstalacaoRepository
    fields:
        idInsucessoInstalacao:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_insucesso_instalacao
            generator:
                strategy: IDENTITY
        teIpComputador:
            type: text
            fixed: true
            nullable: false
            column: te_ip_computador
        teSo:
            type: text
            fixed: false
            nullable: false
            column: te_so
        idUsuario:
            type: text
            fixed: false
            nullable: false
            column: id_usuario
        dtDatahora:
            type: datetime
            nullable: false
            column: dt_datahora
        csIndicador:
            type: text
            fixed: true
            nullable: false
            column: cs_indicador
    lifecycleCallbacks: {  }
