Cacic\CommonBundle\Entity\Local:
    type: entity
    table: local
    repositoryClass: Cacic\CommonBundle\Entity\LocalRepository
    fields:
        idLocal:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_local
            generator:
                strategy: IDENTITY
        nmLocal:
            type: text
            fixed: false
            nullable: false
            column: nm_local
        sgLocal:
            type: text
            fixed: true
            nullable: false
            column: sg_local
        teObservacao:
            type: text
            fixed: false
            nullable: true
            column: te_observacao
        teDebugging:
            type: text
            nullable: true
            column: te_debugging
        dtDebug:
            type: text
            fixed: true
            nullable: true
            column: dt_debug
    manyToMany:
        usuariosSecundarios:
            targetEntity: Usuario
            mappedBy: locaisSecundarios
    oneToMany:
        usuarios:
            targetEntity: Usuario
            mappedBy: idLocal
        redes:
            targetEntity: Rede
            mappedBy: idLocal
        configuracoes:
            targetEntity: ConfiguracaoLocal
            mappedBy: idLocal
    lifecycleCallbacks:
        postPersist: [ configurarFromConfigPadrao ]
