Cacic\CommonBundle\Entity\Notifications:
    type: entity
    table: notifications
    repositoryClass: Cacic\CommonBundle\Entity\NotificationsRepository
    fields:
        idNotification:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_notification
            generator:
                strategy: IDENTITY
        subject:
            type: text
            nullable: false
            column: subject
        fromAddr:
            type: string
            nullable: false
            column: from_addr
        replyTo:
            type: string
            nullable: true
            column: reply_to
        toAddr:
            type: string
            nullable: false
            column: to_addr
        body:
            type: text
            nullable: false
            column: body
        readDate:
            type: datetime
            nullable: true
            column: read_date
        notificationAcao:
            type: text
            nullable: false
            column: notification_acao
        object:
            type: text
            nullable: false
            column: object
    manyToOne:
        idComputador:
            targetEntity: Computador
            cascade: []
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
                    nullable: false
    lifecycleCallbacks: {  }