Cacic\CommonBundle\Entity\SoftwareEstacao:
    type: entity
    table: software_estacao
    repositoryClass: Cacic\CommonBundle\Entity\SoftwareEstacaoRepository
    id:
        idComputador:
            associationKey: true
    fields:
        nrPatrimonio:
            type: text
            fixed: true
            nullable: true
            column: nr_patrimonio
        dtAutorizacao:
            type: date
            nullable: true
            column: dt_autorizacao
        dtExpiracaoInstalacao:
            type: date
            nullable: true
            column: dt_expiracao_instalacao
        idAquisicaoParticular:
            type: integer
            unsigned: false
            nullable: true
            column: id_aquisicao_particular
        dtDesinstalacao:
            type: date
            nullable: true
            column: dt_desinstalacao
        teObservacao:
            type: text
            fixed: false
            nullable: true
            column: te_observacao
        nrPatrDestino:
            type: text
            fixed: true
            nullable: true
            column: nr_patr_destino
    manyToOne:
        idComputador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: softwares
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
        idAquisicaoItem:
            targetEntity: AquisicaoItem
            cascade: {  }
            mappedBy: null
            inversedBy: idSoftwareEstacao
            joinColumns:
                id_tipo_licenca:
                    referencedColumnName: id_tipo_licenca
                id_aquisicao:
                    referencedColumnName: id_aquisicao
            orphanRemoval: false
    lifecycleCallbacks: {  }
