Cacic\CommonBundle\Entity\SoftwareRelatorio:
    type: entity
    table: software_relatorio
    repositoryClass: Cacic\CommonBundle\Entity\SoftwareRelatorioRepository
    fields:
        idRelatorio:
            id: true
            type: integer
            nullable: false
            column: id_relatorio
            generator:
                strategy: IDENTITY
        nomeRelatorio:
            type: text
            fixed: false
            nullable: false
            column: nome_relatorio
        nivelAcesso:
            type: text
            nullable: false
            column: nivel_acesso
        habilitaNotificacao:
            type: boolean
            nullable: true
            column: habilita_notificacao
    manyToMany:
        softwares:
            targetEntity: Software
            mappedBy: relatorios
    manyToOne:
        idUsuario:
            targetEntity: Usuario
            cascade: {}
            inversedBy: relatorios
            joinColumns:
                id_usuario:
                    referencedColumnName: id_usuario
                    nullable: false
    uniqueConstraints:
        software_nm_relatorio_idx:
            columns: [ nome_relatorio ]
    lifecycleCallbacks: {  }