Cacic\CommonBundle\Entity\Software:
    type: entity
    table: software
    repositoryClass: Cacic\CommonBundle\Entity\SoftwareRepository
    fields:
        idSoftware:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_software
            generator:
                strategy: IDENTITY
        nmSoftware:
            type: string
            fixed: false
            column: nm_software
        teDescricaoSoftware:
            type: text
            fixed: false
            nullable: true
            column: te_descricao_software
        qtLicenca:
            type: integer
            unsigned: false
            nullable: true
            column: qt_licenca
        nrMidia:
            type: text
            fixed: true
            nullable: true
            column: nr_midia
        teLocalMidia:
            type: text
            fixed: true
            nullable: true
            column: te_local_midia
        teObs:
            type: text
            fixed: false
            nullable: true
            column: te_obs
    oneToOne:
        idClassProperty:
            targetEntity: ClassProperty
            joinColumn:
                name: id_class_property
                referencedColumnName: id_class_property
                nullable: true
    manyToOne:
        idTipoSoftware:
            targetEntity: TipoSoftware
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_software:
                    referencedColumnName: id_tipo_software
            orphanRemoval: false
    manyToMany:
        aquisicoes:
            targetEntity: AquisicaoItem
            inversedBy: idSoftware
            joinTable:
                name: aquisicoes_software
                joinColumns:
                    id_software:
                        referencedColumnName: id_software
                inverseJoinColumns:
                    id_aquisicao:
                        referencedColumnName: id_aquisicao
                    id_tipo_licenca:
                        referencedColumnName: id_tipo_licenca
        relatorios:
            targetEntity: SoftwareRelatorio
            inversedBy: softwares
            joinTable:
                name: relatorios_software
                joinColumns:
                    id_software:
                        referencedColumnName: id_software
                inverseJoinColumns:
                    id_relatorio:
                        referencedColumnName: id_relatorio
    uniqueConstraints:
            software_nm_software_idx:
                columns: [ nm_software ]
    lifecycleCallbacks: {  }
