Cacic\CommonBundle\Entity\UsbLog:
    type: entity
    table: usb_log
    fields:
        idUsbLog:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_usb_log
            generator:
                strategy: IDENTITY
        dtEvent:
            type: text
            fixed: true
            nullable: false
            column: dt_event
        csEvent:
            type: text
            fixed: true
            nullable: false
            column: cs_event
        idDevice:
            type: text
            fixed: true
            nullable: true
            column: id_device
    manyToOne:
        idUsbDevice:
            targetEntity: UsbDevice
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usb_device:
                    referencedColumnName: id_usb_device
            orphanRemoval: false
        idComputador:
            targetEntity: Computador
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_computador:
                    referencedColumnName: id_computador
            orphanRemoval: false
    lifecycleCallbacks: {  }
