Cacic\CommonBundle\Entity\Usuario:
    type: entity
    table: usuario
    repositoryClass: Cacic\CommonBundle\Entity\UsuarioRepository
    fields:
        idUsuario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_usuario
            generator:
                strategy: IDENTITY
        idUsuarioLdap:
            type: text
            fixed: false
            nullable: true
            column: id_usuario_ldap
        nmUsuarioAcesso:
            type: text
            fixed: true
            nullable: false
            column: nm_usuario_acesso
        nmUsuarioCompleto:
            type: text
            fixed: false
            nullable: false
            column: nm_usuario_completo
        nmUsuarioCompletoLdap:
            type: text
            fixed: false
            nullable: true
            column: nm_usuario_completo_ldap
        teSenha:
            type: text
            fixed: false
            nullable: false
            column: te_senha
        dtLogIn:
            type: datetime
            nullable: true
            column: dt_log_in
        teEmailsContato:
            type: text
            fixed: false
            nullable: true
            column: te_emails_contato
        teTelefonesContato:
            type: text
            fixed: false
            nullable: true
            column: te_telefones_contato
        apiKey:
            type: text
            fixed: false
            nullable: true
            column: api_key
        cryptKey:
            type: text
            fixed: false
            nullable: true
            column: crypt_key
        isActive:
            type: boolean
            fixed: false
            nullable: true
            column: is_active
    manyToMany:
        locaisSecundarios:
            targetEntity: Local
            inversedBy: usuariosSecundarios
            joinTable:
                name: local_secundario
                joinColumns:
                    id_usuario:
                        referencedColumnName: id_usuario
                inverseJoinColumns:
                    id_local:
                        referencedColumnName: id_local
    manyToOne:
        idLocal:
            targetEntity: Local
            cascade: {  }
            mappedBy: null
            inversedBy: usuarios
            joinColumns:
                id_local:
                    referencedColumnName: id_local
                    nullable: false
            orphanRemoval: false
        idServidorAutenticacao:
            targetEntity: ServidorAutenticacao
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_servidor_autenticacao:
                    referencedColumnName: id_servidor_autenticacao
            orphanRemoval: false
        idGrupoUsuario:
            targetEntity: GrupoUsuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_grupo_usuario:
                    referencedColumnName: id_grupo_usuario
                    nullable: false
            orphanRemoval: false
    oneToMany:
        relatorios:
            targetEntity: SoftwareRelatorio
            mappedBy: idUsuario
    uniqueConstraints:
        api_key_uq_idx:
            columns: [ api_key ]
        crypt_key_uq_idx:
            columns: [ crypt_key ]
    lifecycleCallbacks: {  }
